### ISSUE TITLE
Request for input files

### ISSUE THREAD

**Issue by gitCHH** [chai-benchmarks/chai#15]
Where  datasets used in Chai paper are available from ?

**Comment by el1goluj** [comment]
In most benchmarks you can select the desired input. Use -h to find the correct parameters.
In addition, you can find the remaining datasets at:
- CEDD and CEDT's Maradona and Paw:
https://www.youtube.com/watch?v=O8G9ytZg-bM
https://www.youtube.com/watch?v=Q09Rjmhyd6Q
Use converter in utils folder.
- BFS and SSSP: NY and NE belong to 9th DIMACS challenge; UT is a dataset in Parboil benchmark suite.

**Comment by gitCHH** [comment]
For example, only one input Peppa is provided for CEDD. Where I can get other inputs as listed in the paper?

**Comment by el1goluj** [comment]
> CEDD and CEDT's Maradona and Paw:
> https://www.youtube.com/watch?v=O8G9ytZg-bM
> https://www.youtube.com/watch?v=Q09Rjmhyd6Q
> Use converter in utils folder.

**Comment by gitCHH** [comment]
Sorry for my mistake. Maybe, I just don't understand the input of BS.

**Comment by el1goluj** [comment]
The input of BS in control.txt is a set of 16 control points, since the default input size is 4x4.
You can create your own set of control points for bigger or smaller inputs. Actually, for performance evaluation purposes, you can use arbitrary control points. The performance of BS is not input dependent.

**Comment by gitCHH** [comment]
Thank you very much.
